import type { FleetShipRequest, Member, ShipCategoryKey } from './types';

export const categoryFilters: Array<{ key: ShipCategoryKey; label: string }> = [
  { key: 'capital', label: 'Capital' },
  { key: 'subcapital', label: 'Subcapital' },
  { key: 'large', label: 'Large' },
  { key: 'medium', label: 'Medium' },
  { key: 'small', label: 'Small' },
  { key: 'light_fighter', label: 'Light Fighter' },
  { key: 'medium_fighter', label: 'Medium Fighter' },
  { key: 'heavy_fighter', label: 'Heavy Fighter' },
  { key: 'snub_fighter', label: 'Snub Fighter' },
  { key: 'ground_vehicle', label: 'Ground Vehicle' },
];

export const teamFilters = [
  'Alpha',
  'Beta',
  'Charlie',
  'Delta',
  'Echo',
  'Foxtrot',
  'Golf',
  'Hotel',
];

export const fallbackFleetRequests: FleetShipRequest[] = [
  {
    id: 'idris-alpha',
    team: 'Alpha',
    teamKey: 'alpha',
    categoryKey: 'capital',
    categoryName: 'Capital',
    shipName: 'Idris',
    manufacturer: 'Aegis Dynamics',
    requestedCount: 1,
    staffingProfile: 'full_crew',
    requiredPositions: 10,
    optionalPositions: 11,
    assignedPositions: 8,
    pendingSuggestions: 0,
    locked: true,
    exactRequired: true,
    hasMarines: true,
    isAdmiralShip: true,
    notes: 'Fleet command platform with embarked Gamma boarding team.',
    imageUrl: 'https://media.starcitizen.tools/d/dd/Idris_M_flying_over_world_-_cropped.jpg',
  },
  {
    id: 'perseus-alpha',
    team: 'Alpha',
    teamKey: 'alpha',
    categoryKey: 'subcapital',
    categoryName: 'Subcapital',
    shipName: 'Perseus',
    manufacturer: 'Roberts Space Industries',
    requestedCount: 1,
    staffingProfile: 'standard',
    requiredPositions: 3,
    optionalPositions: 3,
    assignedPositions: 2,
    pendingSuggestions: 1,
    locked: false,
    exactRequired: true,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Heavy gunship for external strike phase.',
    imageUrl: 'https://media.starcitizen.tools/6/6c/Perseus_angled_combat.jpg',
  },
  {
    id: 'scorpius-beta',
    team: 'Beta',
    teamKey: 'beta',
    categoryKey: 'heavy_fighter',
    categoryName: 'Heavy Fighter',
    shipName: 'Scorpius',
    manufacturer: 'Roberts Space Industries',
    requestedCount: 2,
    staffingProfile: 'standard',
    requiredPositions: 4,
    optionalPositions: 0,
    assignedPositions: 3,
    pendingSuggestions: 2,
    locked: false,
    exactRequired: false,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Pilots may bring equivalent medium or heavy fighter alternatives.',
    imageUrl: 'https://media.starcitizen.tools/3/30/RSI_Scorpius_on_ArcCorp.png',
  },
  {
    id: 'redeemer-charlie',
    team: 'Charlie',
    teamKey: 'charlie',
    categoryKey: 'large',
    categoryName: 'Large',
    shipName: 'Redeemer',
    manufacturer: 'Aegis Dynamics',
    requestedCount: 1,
    staffingProfile: 'skeleton',
    requiredPositions: 1,
    optionalPositions: 4,
    assignedPositions: 1,
    pendingSuggestions: 0,
    locked: false,
    exactRequired: false,
    hasMarines: true,
    isAdmiralShip: false,
    notes: 'Lean escort with Marines available to transition to FPS.',
    imageUrl: "https://media.starcitizen.tools/5/5c/Redeemer_-_Flying_x2_though_canyon_attacking_Cutlass%27s_-_cropped_and_adjusted.jpg",
  },
  {
    id: 'medical-delta',
    team: 'Delta',
    teamKey: 'delta',
    categoryKey: 'medium',
    categoryName: 'Medium',
    shipName: 'Medical Support Slot',
    manufacturer: 'Any',
    requestedCount: 1,
    staffingProfile: 'custom',
    requiredPositions: 2,
    optionalPositions: 3,
    assignedPositions: 0,
    pendingSuggestions: 3,
    locked: false,
    exactRequired: false,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Open category slot for Cutlass Red, Apollo, or equivalent.',
    imageUrl: 'https://media.starcitizen.tools/a/ac/Cutlass_Red_Squad_Concept.jpg',
  },
];

export const fallbackMembers: Member[] = [
  {
    id: 'm1',
    name: 'ValkyrieActual',
    status: 'ready',
    team: 'Alpha',
    primaryRole: 'Fleet Admiral',
    shipOffer: 'Idris',
  },
  {
    id: 'm2',
    name: 'Cinder',
    status: 'filling',
    team: 'Alpha',
    primaryRole: 'Perseus Pilot',
    shipOffer: 'Perseus',
  },
  {
    id: 'm3',
    name: 'Rook',
    status: 'filling',
    team: 'Beta',
    primaryRole: 'Heavy Fighter Pilot',
    shipOffer: 'Scorpius',
  },
  {
    id: 'm4',
    name: 'Mako',
    status: 'suggesting',
    team: 'Beta',
    primaryRole: 'Turret Gunner',
    shipOffer: 'Hurricane',
  },
  {
    id: 'm5',
    name: 'Patch',
    status: 'standby',
    team: 'Delta',
    primaryRole: 'Medic',
    shipOffer: 'Cutlass Red',
  },
  {
    id: 'm6',
    name: 'Stack',
    status: 'ready',
    team: 'Gamma',
    primaryRole: 'Marine Lead',
  },
];
