import type { FleetCategoryKey, FleetShipRequest, Member } from './types';

export const categoryFilters: Array<{ key: FleetCategoryKey; label: string }> = [
  { key: 'capital', label: 'Capital' },
  { key: 'subcapital', label: 'Subcapital' },
  { key: 'large', label: 'Large' },
  { key: 'medium', label: 'Medium' },
  { key: 'small', label: 'Small' },
  { key: 'light_fighter', label: 'Light Fighter' },
  { key: 'medium_fighter', label: 'Medium Fighter' },
  { key: 'heavy_fighter', label: 'Heavy Fighter' },
  { key: 'snub_fighter', label: 'Snub Fighter' },
  { key: 'ground_vehicle', label: 'Ground Vehicle' },
  { key: 'marines', label: 'Marines' },
];

export const teamFilters = [
  'Unassigned',
  'Alpha',
  'Beta',
  'Charlie',
  'Delta',
  'Echo',
  'Foxtrot',
  'Golf',
  'Hotel',
];

export const fallbackFleetRequests: FleetShipRequest[] = [
  {
    id: 'gamma-marines',
    team: 'Gamma',
    teamKey: 'gamma',
    categoryKey: 'marines',
    categoryName: 'Marines/FPS',
    shipName: 'Marines/FPS',
    manufacturer: 'Fleet Infantry',
    requestedCount: 1,
    staffingProfile: 'custom',
    requiredPositions: 6,
    optionalPositions: 2,
    assignedPositions: 4,
    pendingSuggestions: 1,
    locked: false,
    exactRequired: false,
    hasMarines: true,
    isAdmiralShip: false,
    notes: 'Deployable Marines and medics staged aboard Alpha command ships.',
    crew: [
      { id: 'm6', name: 'Stack', role: 'Marine Lead', status: 'assigned' },
      { id: 'm7', name: 'Breach', role: 'Rifleman', status: 'assigned' },
      { id: 'm8', name: 'DocLine', role: 'Medic', status: 'assigned' },
      { id: 'm9', name: 'Hush', role: 'Scout', status: 'assigned' },
    ],
  },
  {
    id: 'idris-alpha',
    team: 'Alpha',
    teamKey: 'alpha',
    categoryKey: 'capital',
    categoryName: 'Capital',
    shipName: 'Idris',
    manufacturer: 'Aegis Dynamics',
    requestedCount: 1,
    staffingProfile: 'full_crew',
    requiredPositions: 10,
    optionalPositions: 11,
    assignedPositions: 8,
    pendingSuggestions: 0,
    locked: true,
    exactRequired: true,
    hasMarines: true,
    isAdmiralShip: true,
    notes: 'Fleet command platform with embarked Gamma boarding team.',
    imageUrl: 'https://media.starcitizen.tools/d/dd/Idris_M_flying_over_world_-_cropped.jpg',
    ownerName: 'THE_PRIME',
    crew: [
      { id: 'm1', name: 'ValkyrieActual', role: 'Fleet Admiral', status: 'assigned' },
      { id: 'c-idris-1', name: 'Hammer', role: 'Turret Gunner', status: 'assigned' },
      { id: 'c-idris-2', name: 'Warden', role: 'Engineer', status: 'assigned' },
      { id: 'c-idris-3', name: 'Bulwark', role: 'Turret Gunner', status: 'assigned' },
    ],
  },
  {
    id: 'perseus-alpha',
    team: 'Alpha',
    teamKey: 'alpha',
    categoryKey: 'subcapital',
    categoryName: 'Subcapital',
    shipName: 'Perseus',
    manufacturer: 'Roberts Space Industries',
    requestedCount: 1,
    staffingProfile: 'standard',
    requiredPositions: 3,
    optionalPositions: 3,
    assignedPositions: 2,
    pendingSuggestions: 1,
    locked: false,
    exactRequired: true,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Heavy gunship for external strike phase.',
    imageUrl: 'https://media.starcitizen.tools/6/6c/Perseus_angled_combat.jpg',
    ownerName: 'Cinder',
    crew: [
      { id: 'm2', name: 'Cinder', role: 'Pilot', status: 'assigned' },
      { id: 'c-perseus-1', name: 'Graves', role: 'Turret Gunner', status: 'requested' },
    ],
  },
  {
    id: 'scorpius-beta',
    team: 'Beta',
    teamKey: 'beta',
    categoryKey: 'heavy_fighter',
    categoryName: 'Heavy Fighter',
    shipName: 'Scorpius',
    manufacturer: 'Roberts Space Industries',
    requestedCount: 1,
    staffingProfile: 'standard',
    requiredPositions: 4,
    optionalPositions: 0,
    assignedPositions: 3,
    pendingSuggestions: 2,
    locked: false,
    exactRequired: false,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Pilots may bring equivalent medium or heavy fighter alternatives.',
    imageUrl: 'https://media.starcitizen.tools/3/30/RSI_Scorpius_on_ArcCorp.png',
    ownerName: 'Rook',
    crew: [
      { id: 'm3', name: 'Rook', role: 'Pilot', status: 'assigned' },
      { id: 'm4', name: 'Mako', role: 'Turret Gunner', status: 'assigned' },
    ],
  },
  {
    id: 'scorpius-beta-open',
    team: 'Beta',
    teamKey: 'beta',
    categoryKey: 'heavy_fighter',
    categoryName: 'Heavy Fighter',
    shipName: 'Heavy Fighter Request',
    manufacturer: 'Any',
    requestedCount: 1,
    staffingProfile: 'standard',
    requiredPositions: 1,
    optionalPositions: 1,
    assignedPositions: 0,
    pendingSuggestions: 1,
    locked: false,
    exactRequired: false,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Open heavy fighter type request. Scorpius and Hurricane need a turret gunner.',
    imageUrl: 'https://media.starcitizen.tools/3/30/RSI_Scorpius_on_ArcCorp.png',
    crew: [{ id: 'c-scorpius-open-1', name: 'Open', role: 'Pilot', status: 'requested' }],
  },
  {
    id: 'redeemer-charlie',
    team: 'Charlie',
    teamKey: 'charlie',
    categoryKey: 'large',
    categoryName: 'Large',
    shipName: 'Redeemer',
    manufacturer: 'Aegis Dynamics',
    requestedCount: 1,
    staffingProfile: 'skeleton',
    requiredPositions: 1,
    optionalPositions: 4,
    assignedPositions: 1,
    pendingSuggestions: 0,
    locked: false,
    exactRequired: false,
    hasMarines: true,
    isAdmiralShip: false,
    notes: 'Lean escort with Marines available to transition to FPS.',
    imageUrl: "https://media.starcitizen.tools/5/5c/Redeemer_-_Flying_x2_though_canyon_attacking_Cutlass%27s_-_cropped_and_adjusted.jpg",
    ownerName: 'Breach',
    crew: [{ id: 'c-redeemer-1', name: 'Breach', role: 'Pilot', status: 'assigned' }],
  },
  {
    id: 'medical-delta',
    team: 'Delta',
    teamKey: 'delta',
    categoryKey: 'medium',
    categoryName: 'Medium',
    shipName: 'Medical Support Request',
    manufacturer: 'Any',
    requestedCount: 1,
    staffingProfile: 'custom',
    requiredPositions: 2,
    optionalPositions: 3,
    assignedPositions: 0,
    pendingSuggestions: 3,
    locked: false,
    exactRequired: false,
    hasMarines: false,
    isAdmiralShip: false,
    notes: 'Open category slot for Cutlass Red, Apollo, or equivalent.',
    imageUrl: 'https://media.starcitizen.tools/a/ac/Cutlass_Red_Squad_Concept.jpg',
    crew: [{ id: 'm5', name: 'Patch', role: 'Medic', status: 'requested' }],
  },
];

export const fallbackMembers: Member[] = [
  {
    id: 'm1',
    name: 'ValkyrieActual',
    status: 'ready',
    operationRole: 'fleet_admiral',
    team: 'Alpha',
    primaryRole: 'Fleet Admiral',
    shipOffer: 'Idris',
    assignedRequestId: 'idris-alpha',
  },
  {
    id: 'm2',
    name: 'Cinder',
    status: 'filling',
    operationRole: 'officer',
    team: 'Alpha',
    primaryRole: 'Perseus Pilot',
    shipOffer: 'Perseus',
    assignedRequestId: 'perseus-alpha',
  },
  {
    id: 'm3',
    name: 'Rook',
    status: 'filling',
    operationRole: 'crew',
    team: 'Beta',
    primaryRole: 'Heavy Fighter Pilot',
    shipOffer: 'Scorpius',
    assignedRequestId: 'scorpius-beta',
  },
  {
    id: 'm4',
    name: 'Mako',
    status: 'suggesting',
    operationRole: 'crew',
    team: 'Beta',
    primaryRole: 'Turret Gunner',
    shipOffer: 'Hurricane',
    assignedRequestId: 'scorpius-beta',
  },
  {
    id: 'm5',
    name: 'Patch',
    status: 'standby',
    operationRole: 'crew',
    team: 'Delta',
    primaryRole: 'Medic',
    shipOffer: 'Cutlass Red',
  },
  {
    id: 'm6',
    name: 'Stack',
    status: 'ready',
    operationRole: 'crew',
    team: 'Gamma',
    primaryRole: 'Marine Lead',
    assignedRequestId: 'gamma-marines',
  },
  {
    id: 'm7',
    name: 'J3rry',
    status: 'ready',
    operationRole: 'crew',
    team: 'Unassigned',
    primaryRole: 'Fleet Organizer',
  },
];
